"use client";

import { useState } from "react";
import Image from "next/image";
import styles from "./page.module.css";

export default function HomePage() {
  const [loading, setLoading] = useState(false);

  const handleDownload = async () => {
    setLoading(true);
    const res = await fetch("/api/generate-pptx");
    const blob = await res.blob();
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "The_Dependencies_Dilemma_Slide.pptx";
    a.click();
    window.URL.revokeObjectURL(url);
    setLoading(false);
  };

  return (
    <main>
      <h1>POC: PPTXGenJS</h1>
      <p>
        This application demonstrates working with the <code>pptxgenjs</code> library to generate a PowerPoint slide programmatically. When you click the &ldquo;Generate slide&rdquo; button, a PowerPoint slide is created and ready for download.
      </p>

      <h2>Example PowerPoint Slide</h2>
      <p>This is an example of the slide generated by the application:</p>
      <Image src="/The_Dependencies_Dilemma_Slide_example.png" alt="Example PowerPoint Slide" width={600} height={400} priority />

      <button onClick={handleDownload} disabled={loading} className={styles["generate-button"]}>
        {loading ? "Generation..." : "Generate slide"}
      </button>
    </main>
  );
}
