"use client";

import { useState } from "react";
import Image from "next/image";
import styles from "./page.module.css";

export default function GenerateSlidePage() {
  const [loading, setLoading] = useState(false);

  const handleDownload = async () => {
    try {
      setLoading(true);

      const res = await fetch("/api/generate-pptx");

      if (!res.ok) {
        throw new Error(`Download failed: ${res.statusText}`);
      }

      const blob = await res.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");

      a.href = url;
      a.download = "The_Dependencies_Dilemma_Slide.pptx";
      a.click();

      window.URL.revokeObjectURL(url);
    } catch (error) {
      console.error("Download error:", error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <main>
      <h1>POC: PPTXGenJS</h1>
      <p>
        This application demonstrates working with the <code>pptxgenjs</code> library to generate a PowerPoint slide programmatically. When you click the &ldquo;Generate slide&rdquo; button, a PowerPoint slide is created and ready for download.
      </p>

      <h2>Example PowerPoint Slide</h2>
      <p>This is an example of the slide generated by the application:</p>
      <Image src="/image/the_dependencies_dilemma_slide_example.png" alt="Example PowerPoint Slide" width={600} height={400} priority />

      <button onClick={handleDownload} disabled={loading} className={styles["generate-button"]}>
        {loading ? "Generation..." : "Generate slide"}
      </button>
    </main>
  );
}
